"use server";
import puppeteer from "puppeteer";
import { marked } from "marked";
import { PolicyVariant } from "@repo/database";
import { escapeHtml, sanitize } from "@/utils/sanatize";
type CompanyProfile = {
  name: string;
  industry: string;
  size: string;
  countries: string;
};
const VARIANT_LABELS: Record<string, string> = {
  EXECUTIVE_SUMMARY: "Executive Summary",
  COMPREHENSIVE_POLICY: "Comprehensive Policy",
  VENDOR_REQUIREMENTS: "Vendor Requirements",
  CODING_STANDARDS: "Coding Standards",
};
export async function generateVariantPDF(
  company: CompanyProfile,
  variant: PolicyVariant
) {
  const browser = await puppeteer.launch({
    headless: true,
  });
  const page = await browser.newPage();
  // Convert markdown content → HTML
  const contentHtml = await marked.setOptions({ breaks: true, gfm: true }).parse(variant.content);
  const safeContentHtml = sanitize(contentHtml);
  const variantLabel = escapeHtml(VARIANT_LABELS[variant.variantType] || variant.variantType.replace(/_/g, " "));
  const html = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      @page {
        margin: 80px 40px;
      }
      body {
        font-family: Helvetica, Arial, sans-serif;
        color: #1a1a1a;
        line-height: 1.6;
      }
      h1, h2, h3 {
        color: #0f766e;
      }
      .cover {
        height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        page-break-after: always;
      }
      .cover h1 {
        font-size: 42px;
        margin-bottom: 10px;
      }
      .cover h2 {
        font-size: 28px;
        color: #0f766e;
        margin-bottom: 20px;
      }
      .meta {
        margin-top: 20px;
        font-size: 14px;
      }
      .content {
        padding: 20px 0;
      }
      footer {
        position: fixed;
        bottom: 20px;
        left: 40px;
        right: 40px;
        font-size: 12px;
        color: #666;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <!-- Cover -->
    <div class="cover">
      <h1>${company.name}</h1>
      <h2>${variantLabel}</h2>
      <div class="meta">
        <p><strong>Variant Type:</strong> ${variantLabel}</p>
        <p><strong>Generated:</strong> ${new Date(variant.generatedAt).toDateString()}</p>
        <p><strong>Industry:</strong> ${company.industry}</p>
      </div>
    </div>
    <!-- Content -->
    <div class="content">
      ${safeContentHtml}
    </div>
    <!-- Footer -->
    <footer>
      <span>Generated by Mandate</span>
      <span>${new Date().toDateString()}</span>
    </footer>
  </body>
  </html>
  `;
  await page.setContent(html, {
    waitUntil: "networkidle0",
  });
  const pdf = await page.pdf({
    format: "A4",
    printBackground: true,
    displayHeaderFooter: true,
    footerTemplate: `
      <div style="width:100%; font-size:10px; padding:0 20px; color:#666; display:flex; justify-content:space-between;">
        <span>Generated by Mandate</span>
        <span class="pageNumber"></span>/<span class="totalPages"></span>
      </div>
    `,
    headerTemplate: `<div></div>`,
    margin: {
      top: "80px",
      bottom: "80px",
    },
  });
  await browser.close();
  return pdf;
}