"use server";
import puppeteer from "puppeteer";
import { marked } from "marked";
import { Policy } from "@repo/database";
import { escapeHtml, sanitize } from "@/utils/sanatize";

type CompanyProfile = {
  name: string;
  industry: string;
  size: string;
  countries: string;
};

type Section = {
  title: string;
  content: string;
};

export async function generatePolicyPDF(
  company: CompanyProfile,
  policy: Policy
) {
  const browser = await puppeteer.launch({
    headless: true,
  });

  const page = await browser.newPage();

  // Convert markdown sections → HTML
  const sectionsHtml = (policy.sections as Section[])
    .map(
      (section, index) => `
      <div class="section">
        <h2>${index + 1}. ${section.title}</h2>
        ${marked.setOptions({ breaks: true, gfm: true }).parse(section.content)}
      </div>
    `
    )
    .join("");

  const safeSectionsHtml = sanitize(sectionsHtml);

  // TOC generation
  const tocHtml = (policy.sections as Section[])
    .map(
      (section, index) => `
      <div class="toc-item">
        <span>${index + 1}. ${escapeHtml(section.title)}</span>
      </div>
    `
    )
    .join("");

  const html = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      @page {
        margin: 80px 40px;
      }

      body {
        font-family: Helvetica, Arial, sans-serif;
        color: #1a1a1a;
        line-height: 1.6;
      }

      h1, h2, h3 {
        color: #0f766e;
      }

      .cover {
        height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        page-break-after: always;
      }

      .cover h1 {
        font-size: 42px;
        margin-bottom: 10px;
      }

      .meta {
        margin-top: 20px;
        font-size: 14px;
      }

      .toc {
        page-break-after: always;
      }

      .toc h2 {
        margin-bottom: 20px;
      }

      .toc-item {
        margin-bottom: 8px;
      }

      .section {
        page-break-before: always;
      }

      footer {
        position: fixed;
        bottom: 20px;
        left: 40px;
        right: 40px;
        font-size: 12px;
        color: #666;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>

  <body>
    <!-- Cover -->
    <div class="cover">
      <h1>${company.name}</h1>
      <h2>Policy Document</h2>

      <div class="meta">
        <p><strong>Version:</strong> ${policy.version}</p>
        <p><strong>Status:</strong> ${policy.status}</p>
        <p><strong>Date:</strong> ${new Date().toDateString()}</p>
        <p><strong>Industry:</strong> ${company.industry}</p>
      </div>
    </div>

    <!-- TOC -->
    <div class="toc">
      <h2>Table of Contents</h2>
      ${tocHtml}
    </div>

    <!-- Sections -->
    ${safeSectionsHtml}

    <!-- Footer -->
    <footer>
      <span>Generated by Mandate</span>
      <span>${new Date().toDateString()}</span>
    </footer>
  </body>
  </html>
  `;

  await page.setContent(html, {
    waitUntil: "networkidle0",
  });

  const pdf = await page.pdf({
    format: "A4",
    printBackground: true,
    displayHeaderFooter: true,
    footerTemplate: `
      <div style="width:100%; font-size:10px; padding:0 20px; color:#666; display:flex; justify-content:space-between;">
        <span>Generated by Mandate</span>
        <span class="pageNumber"></span>/<span class="totalPages"></span>
      </div>
    `,
    headerTemplate: `<div></div>`,
    margin: {
      top: "80px",
      bottom: "80px",
    },
  });

  await browser.close();

  return pdf;
}